var words = [
    { engWord:  'Bathroom', rusWord: ' Ванная' },
    { engWord:  'Wait', rusWord: ' Ждать' },
    { engWord:  'Ride', rusWord: ' Поездка' },
    { engWord:  'Sometimes', rusWord: ' Иногда' },
    { engWord:  'Hurry', rusWord: ' Спешить' },
    { engWord:  'After', rusWord: ' После' },
    { engWord: ' Wash', rusWord: ' Мыть' },
    { engWord: ' Already', rusWord: ' Уже' },
    { engWord: ' Listen', rusWord: ' Слушать' },
    { engWord: ' Seldom', rusWord: ' Редко' },
    { engWord: ' Divide', rusWord: ' Разбивать' },
    { engWord: ' According', rusWord: 'В соответствии  ' },
    { engWord: ' Although', rusWord: ' Несмотря на то что' },
    { engWord: ' Forehead', rusWord: ' Лоб' },
    { engWord: ' Ear', rusWord: ' Ухо' },
    { engWord: ' Chin', rusWord: ' Подбородок' },
    { engWord: ' Shoulder', rusWord: ' Плечо' },
    { engWord: ' Elbow', rusWord: ' Локоть' },
    { engWord: ' Forearm', rusWord: ' Предплечье' },
    { engWord: ' Wrist', rusWord: ' Запястье' },
    { engWord: ' Hand', rusWord: ' Кисть' },
    { engWord: ' Palm', rusWord: ' Ладонь' },
    { engWord: ' Finger', rusWord: ' Палец руки' },
    { engWord: ' Calf', rusWord: ' Голень/икра' },
    { engWord: ' Ankle', rusWord: ' Лодыжка' },
    { engWord: ' Heel', rusWord: ' Пятка' },
    { engWord: ' Head', rusWord: ' Голова' },
    { engWord: ' Neck', rusWord: ' Шея' },
    { engWord: ' Chest', rusWord: ' Грудь' },
    { engWord: ' Breast', rusWord: ' Грудь'},
    { engWord: ' Arm', rusWord: ' Рука' },
    { engWord: ' Waist', rusWord: ' Талия' },
    { engWord: ' Stomach', rusWord: ' Живот' },
    { engWord: ' Belly button', rusWord: ' Пупок' },
    { engWord: ' Pelvis', rusWord: ' Таз' },
    { engWord: ' Thigh', rusWord: ' Бедро' },
    { engWord: ' Leg', rusWord: ' Нога' },
    { engWord: ' Knee', rusWord: ' Колено' },
    { engWord: ' Shin', rusWord: ' Голень' },
    { engWord: ' Foot', rusWord: ' Нога' },
    { engWord: ' Toe', rusWord: ' Палец ноги' },
    { engWord: ' Wellies ', rusWord: ' Сапоги' },
    { engWord: ' Umbrella', rusWord: ' Зонтик' },
    { engWord: ' Usually ', rusWord: ' Как правило/обычно' },
    { engWord: ' Want', rusWord: ' Хотеть' },
    { engWord: ' Nearby ', rusWord: ' Рядом' },
    { engWord: ' Therefore', rusWord: ' Следовательно' },
    { engWord: ' Aunt', rusWord: ' Тётка' },
    { engWord: ' Shirt', rusWord: ' Рубашка' },
    { engWord: ' T-shirt', rusWord: ' Футболка' },
    { engWord: ' While ', rusWord: ' В то время как' },
    { engWord: ' Tie', rusWord: ' Галстук' },
    { engWord: ' Excited', rusWord: ' Восторг' },
    { engWord: ' Schedule/timetable ', rusWord: ' Список' },
    { engWord: ' Evening', rusWord: ' Вечер' },
    { engWord: ' Dinner ', rusWord: ' Ужин' },
    { engWord: ' Improve ', rusWord: ' Улучшать' },
    { engWord: ' Disappear', rusWord: ' Исчезать' },
    { engWord: ' Hugs ', rusWord: ' Объятия' },
    { engWord: ' Candle ', rusWord: ' Свеча' },
    { engWord: ' Escape ', rusWord: ' Побег' },
    { engWord: ' Weak', rusWord: ' Cлабый' },
    { engWord: ' Expectation ', rusWord: ' Ожидание ' },
    { engWord: ' Exhaust ', rusWord: ' Выхлоп ' },
    { engWord: ' Everyone ', rusWord: ' Любой ' },
    { engWord: ' Surrender ', rusWord: ' Сдача ' },
    { engWord: ' Shackle ', rusWord: ' Оковы ' },
    { engWord: ' Silence ', rusWord: ' Молчание ' },
    { engWord: ' Whatever ', rusWord: ' Все ' },
    { engWord: ' Whine ', rusWord: ' Ныть' },
    { engWord: ' Walk ', rusWord: ' Идти ' },
    { engWord: ' Cause ', rusWord: ' Причина ' },
    { engWord: ' Carry ', rusWord: ' Проводить ' },
    { engWord: ' Cave ', rusWord: ' Пещера ' },
    { engWord: ' Tangible ', rusWord: ' Материальный ' },
    { engWord: ' Trident ', rusWord: ' Трезубец ' },
    { engWord: ' Tumble ', rusWord: ' Упасть ' }
]
	
	
	

	
